#!/usr/bin/env python3
"""Reproducibly package first-party CAD examples for dependency-free file:// use."""
import importlib.util
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / 'tests/fixtures/generated-unit-cube-m.step').read_text()
target = ROOT / 'web/examples/cube.js'
target.parent.mkdir(exist_ok=True)
target.write_text('// Generated by tools/build-examples.py from the analytical CAD fixture.\n'
                  'globalThis.SpjutsimFEA.EXAMPLE_CUBE_STEP = ' + json.dumps(source) + ';\n')

spec = importlib.util.spec_from_file_location('validation_geometry', ROOT / 'tools/generate-validation-geometry.py')
geometry = importlib.util.module_from_spec(spec)
spec.loader.exec_module(geometry)
beam = geometry.faceted_prism('cantilever-beam', [(0, 0), (2, 0), (2, 0.2), (0, 0.2)], 0.1)
(target.parent / 'cantilever.js').write_text(
    '// Generated by tools/build-examples.py: 2000 x 200 x 100 mm rectangular beam.\n'
    'globalThis.SpjutsimFEA.EXAMPLE_CANTILEVER_STEP = ' + json.dumps(beam) + ';\n')
