#!/usr/bin/env python3
"""Package the first-party analytical cube for dependency-free file:// examples."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / 'tests/fixtures/generated-unit-cube-m.step').read_text()
target = ROOT / 'web/examples/cube.js'
target.parent.mkdir(exist_ok=True)
target.write_text('// Generated by tools/build-examples.py from the analytical CAD fixture.\n'
                  'globalThis.SpjutsimFEA.EXAMPLE_CUBE_STEP = ' + json.dumps(source) + ';\n')
