#!/usr/bin/env python3
"""Generate file-safe Blob-worker source wrappers from readable worker sources."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXPECTED_PROTOCOL_VERSION = 1
WORKERS = {
    'mesher': 'mesher-worker.js',
    'solver': 'solver-worker.js',
}
PROTOCOL_PATTERN = re.compile(r'\bWORKER_PROTOCOL_VERSION\s*=\s*(\d+)\s*;')


def read_worker_source(source_root: Path, kind: str, filename: str) -> tuple[str, str]:
    path = source_root / filename
    try:
        source = path.read_text(encoding='utf-8')
    except OSError as error:
        raise ValueError(f'{kind} worker source is unavailable: {path}') from error

    match = PROTOCOL_PATTERN.search(source)
    if match is None:
        raise ValueError(f'{kind} worker does not declare WORKER_PROTOCOL_VERSION')
    if int(match.group(1)) != EXPECTED_PROTOCOL_VERSION:
        raise ValueError(
            f'{kind} worker protocol is {match.group(1)}, expected {EXPECTED_PROTOCOL_VERSION}'
        )
    return source, hashlib.sha256(source.encode('utf-8')).hexdigest()


def render_wrapper(kind: str, filename: str, source: str, checksum: str) -> str:
    payload = json.dumps(source, ensure_ascii=False)
    return f'''/*
 * Generated by tools/build-local-runtime.py; do not edit by hand.
 * Source: workers/{filename}
 * Source SHA-256: {checksum}
 * Worker protocol: {EXPECTED_PROTOCOL_VERSION}
 */
(function (root) {{
  'use strict';
  var runtime = root.SpjutsimLocalRuntimeWorkers = root.SpjutsimLocalRuntimeWorkers || {{}};
  runtime.{kind} = {payload};
}}(globalThis));
'''


def build(source_root: Path, output_dir: Path) -> None:
    generated = []
    for kind, filename in WORKERS.items():
        source, checksum = read_worker_source(source_root, kind, filename)
        generated.append((f'{kind}-worker-source.js', render_wrapper(kind, filename, source, checksum)))

    output_dir.mkdir(parents=True, exist_ok=True)
    for filename, contents in generated:
        (output_dir / filename).write_text(contents, encoding='utf-8')


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-root', type=Path, default=ROOT / 'workers')
    parser.add_argument('--output-dir', type=Path, default=ROOT / 'web/generated/local-runtime')
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        build(args.source_root, args.output_dir)
    except ValueError as error:
        print(f'local runtime generation failed: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
