#!/usr/bin/env python3
"""Generate file-safe Blob-worker source wrappers from readable worker sources."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Optional


ROOT = Path(__file__).resolve().parents[1]
EXPECTED_PROTOCOL_VERSION = 2
WORKERS = {
    'mesher': 'mesher-worker.js',
    'solver': 'solver-worker.js',
}
PROTOCOL_PATTERN = re.compile(r'\bWORKER_PROTOCOL_VERSION\s*=\s*(\d+)\s*;')
GMSH_RUNTIME_EXPORT = 'export function buildApi'
DEFAULT_GMSH_PART_CHARACTERS = 8 * 1024 * 1024
CLOUDFLARE_STATIC_ASSET_LIMIT_BYTES = 25 * 1024 * 1024


def read_worker_source(source_root: Path, kind: str, filename: str) -> tuple[str, str]:
    path = source_root / filename
    try:
        source = path.read_text(encoding='utf-8')
    except OSError as error:
        raise ValueError(f'{kind} worker source is unavailable: {path}') from error

    match = PROTOCOL_PATTERN.search(source)
    if match is None:
        raise ValueError(f'{kind} worker does not declare WORKER_PROTOCOL_VERSION')
    if int(match.group(1)) != EXPECTED_PROTOCOL_VERSION:
        raise ValueError(
            f'{kind} worker protocol is {match.group(1)}, expected {EXPECTED_PROTOCOL_VERSION}'
        )
    return source, hashlib.sha256(source.encode('utf-8')).hexdigest()


def render_wrapper(kind: str, filename: str, source: str, checksum: str) -> str:
    payload = json.dumps(source, ensure_ascii=False)
    return f'''/*
 * Generated by tools/build-local-runtime.py; do not edit by hand.
 * Source: workers/{filename}
 * Source SHA-256: {checksum}
 * Worker protocol: {EXPECTED_PROTOCOL_VERSION}
 */
(function (root) {{
  'use strict';
  var runtime = root.SpjutsimLocalRuntimeWorkers = root.SpjutsimLocalRuntimeWorkers || {{}};
  runtime.{kind} = {payload};
}}(globalThis));
'''


def render_gmsh_part(index: int, source: str) -> str:
    payload = json.dumps(source, ensure_ascii=False)
    return f'''/*
 * Generated by tools/build-local-runtime.py; do not edit by hand.
 * Pinned serial Gmsh/OpenCASCADE runtime source part {index + 1}.
 */
(function (root) {{
  'use strict';
  var runtime = root.SpjutsimLocalRuntimeWorkers = root.SpjutsimLocalRuntimeWorkers || {{}};
  runtime.gmshParts = runtime.gmshParts || [];
  runtime.gmshParts[{index}] = {payload};
}}(globalThis));
'''


def render_gmsh_wrapper(core: str, runtime: str, descriptor: str, part_characters: int) -> dict[str, str]:
    if 'createGmshModule' not in core:
        raise ValueError('Gmsh core does not declare createGmshModule')
    if 'SharedArrayBuffer' in core or 'PThread' in core:
        raise ValueError('Gmsh core is not a serial WASM build')
    if GMSH_RUNTIME_EXPORT not in runtime:
        raise ValueError('Gmsh runtime does not export buildApi')
    try:
        json.loads(descriptor)
    except json.JSONDecodeError as error:
        raise ValueError('Gmsh API descriptor is not valid JSON') from error

    runtime = runtime.replace(GMSH_RUNTIME_EXPORT, 'function buildApi', 1)
    source = f'''{core}
{runtime}
var SPJUTSIM_GMSH_DESCRIPTOR = {descriptor.strip()};
async function initializeSpjutsimGmsh(moduleOverrides) {{
  var Module = await createGmshModule(moduleOverrides || {{}});
  var api = buildApi(Module, SPJUTSIM_GMSH_DESCRIPTOR);
  api.FS = Module.FS;
  api.module = Module;
  return api;
}}
'''
    checksums = {
        'core': hashlib.sha256(core.encode('utf-8')).hexdigest(),
        'runtime': hashlib.sha256(runtime.encode('utf-8')).hexdigest(),
        'descriptor': hashlib.sha256(descriptor.encode('utf-8')).hexdigest(),
        'payload': hashlib.sha256(source.encode('utf-8')).hexdigest(),
    }
    metadata = json.dumps({
        'gmshJs': 'v0.3.0',
        'gmshJsCommit': '3fdabeeb1dac2417446cefb9f75ecb6645315cd6',
        'gmshCommit': '29726e7237db13ff77ef3f2db2d7fb9499c4e65c',
        'occtVersion': '7.8.1',
        'emscriptenVersion': '3.1.74',
        'threaded': False,
        'networkRequired': False,
        'checksums': checksums,
    }, sort_keys=True)
    chunks = [source[offset:offset + part_characters] for offset in range(0, len(source), part_characters)]
    rendered = {
        f'gmsh-runtime-source-part-{index + 1:03d}.js': render_gmsh_part(index, chunk)
        for index, chunk in enumerate(chunks)
    }
    rendered['gmsh-runtime-source.js'] = f'''/*
 * Generated by tools/build-local-runtime.py; do not edit by hand.
 * Pinned serial Gmsh/OpenCASCADE runtime manifest for direct-local workers.
 */
(function (root) {{
  'use strict';
  var runtime = root.SpjutsimLocalRuntimeWorkers = root.SpjutsimLocalRuntimeWorkers || {{}};
  runtime.gmshPartCount = {len(chunks)};
  runtime.gmshMetadata = {metadata};
}}(globalThis));
'''
    oversized = [
        filename for filename, contents in rendered.items()
        if len(contents.encode('utf-8')) > CLOUDFLARE_STATIC_ASSET_LIMIT_BYTES
    ]
    if oversized:
        raise ValueError('generated Gmsh assets exceed the 25 MiB static-asset limit: ' + ', '.join(oversized))
    return rendered


def render_fem_wrapper(source: str) -> str:
    if 'createSpjutsimFemModule' not in source:
        raise ValueError('FEM runtime does not declare createSpjutsimFemModule')
    checksum = hashlib.sha256(source.encode('utf-8')).hexdigest()
    payload = json.dumps(source, ensure_ascii=False)
    return f'''/*
 * Generated by tools/build-local-runtime.py; do not edit by hand.
 * First-party single-file FEM WebAssembly runtime.
 * Source SHA-256: {checksum}
 */
(function (root) {{
  'use strict';
  var runtime = root.SpjutsimLocalRuntimeWorkers = root.SpjutsimLocalRuntimeWorkers || {{}};
  runtime.fem = {payload};
  runtime.femMetadata = {{"apiVersion": 1, "threaded": false, "networkRequired": false, "sha256": "{checksum}"}};
}}(globalThis));
'''


def build(source_root: Path, output_dir: Path, fem_runtime: Optional[Path] = None) -> None:
    generated = []
    for kind, filename in WORKERS.items():
        source, checksum = read_worker_source(source_root, kind, filename)
        generated.append((f'{kind}-worker-source.js', render_wrapper(kind, filename, source, checksum)))

    output_dir.mkdir(parents=True, exist_ok=True)
    for filename, contents in generated:
        (output_dir / filename).write_text(contents, encoding='utf-8')
    if fem_runtime is not None:
        try:
            fem_source = fem_runtime.read_text(encoding='utf-8')
        except OSError as error:
            raise ValueError(f'FEM runtime input is unavailable: {fem_runtime}') from error
        (output_dir / 'fem-runtime-source.js').write_text(render_fem_wrapper(fem_source), encoding='utf-8')


def build_gmsh(
    core_path: Path,
    runtime_path: Path,
    descriptor_path: Path,
    output_dir: Path,
    part_characters: int = DEFAULT_GMSH_PART_CHARACTERS,
) -> None:
    if part_characters <= 0:
        raise ValueError('Gmsh part character count must be positive')
    try:
        core = core_path.read_text(encoding='utf-8')
        runtime = runtime_path.read_text(encoding='utf-8')
        descriptor = descriptor_path.read_text(encoding='utf-8')
    except OSError as error:
        raise ValueError(f'Gmsh runtime input is unavailable: {error.filename}') from error

    output_dir.mkdir(parents=True, exist_ok=True)
    rendered = render_gmsh_wrapper(core, runtime, descriptor, part_characters)
    for stale_part in output_dir.glob('gmsh-runtime-source-part-*.js'):
        stale_part.unlink()
    for filename, contents in rendered.items():
        (output_dir / filename).write_text(contents, encoding='utf-8')


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-root', type=Path, default=ROOT / 'workers')
    parser.add_argument('--output-dir', type=Path, default=ROOT / 'web/generated/local-runtime')
    parser.add_argument('--gmsh-core', type=Path)
    parser.add_argument('--gmsh-runtime', type=Path)
    parser.add_argument('--gmsh-descriptor', type=Path)
    parser.add_argument('--gmsh-part-characters', type=int, default=DEFAULT_GMSH_PART_CHARACTERS)
    parser.add_argument('--fem-runtime', type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        build(args.source_root, args.output_dir, args.fem_runtime)
        gmsh_inputs = (args.gmsh_core, args.gmsh_runtime, args.gmsh_descriptor)
        if any(gmsh_inputs):
            if not all(gmsh_inputs):
                raise ValueError('all three Gmsh runtime inputs must be provided')
            build_gmsh(*gmsh_inputs, args.output_dir, args.gmsh_part_characters)
    except ValueError as error:
        print(f'local runtime generation failed: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
