#!/usr/bin/env python3
"""Generate deterministic CalculiX C3D8 reference decks for v1 benchmarks."""

from __future__ import annotations

import argparse
import pathlib


CASES = {
    "axial-traction": {"size": (1.0, 1.0, 1.0), "divisions": (8, 8, 8), "kind": "axial"},
    "cantilever-bending": {"size": (4.0, 0.25, 0.5), "divisions": (64, 4, 8), "kind": "bending"},
    "uniform-pressure": {"size": (1.0, 1.0, 1.0), "divisions": (8, 8, 8), "kind": "pressure"},
    "gravity-reaction": {"size": (1.0, 1.0, 1.0), "divisions": (8, 8, 8), "kind": "gravity"},
    "notched-prism-stress": {"size": (3.0, 1.0, 0.2), "divisions": (60, 20, 4), "kind": "notch"},
}


def format_set(name: str, values: list[int]) -> list[str]:
    lines = [f"*NSET, NSET={name}"]
    for start in range(0, len(values), 16):
        lines.append(", ".join(str(value) for value in values[start : start + 16]))
    return lines


def generate_case(case_id: str, definition: dict) -> str:
    lx, ly, lz = definition["size"]
    nx, ny, nz = definition["divisions"]
    kind = definition["kind"]
    coordinates = {}
    elements = []
    element_centers = []
    used = set()

    def node_id(i: int, j: int, k: int) -> int:
        return 1 + i + (nx + 1) * (j + (ny + 1) * k)

    for k in range(nz + 1):
        for j in range(ny + 1):
            for i in range(nx + 1):
                coordinates[node_id(i, j, k)] = (lx * i / nx, ly * j / ny, lz * k / nz)
    for k in range(nz):
        for j in range(ny):
            for i in range(nx):
                cx = lx * (i + 0.5) / nx
                cy = ly * (j + 0.5) / ny
                if kind == "notch" and 1.2 < cx < 1.8 and cy > 0.7:
                    continue
                nodes = (
                    node_id(i, j, k), node_id(i + 1, j, k),
                    node_id(i + 1, j + 1, k), node_id(i, j + 1, k),
                    node_id(i, j, k + 1), node_id(i + 1, j, k + 1),
                    node_id(i + 1, j + 1, k + 1), node_id(i, j + 1, k + 1),
                )
                elements.append(nodes)
                element_centers.append((cx, cy, lz * (k + 0.5) / nz))
                used.update(nodes)
    nodes = sorted(used)
    xmin = [node for node in nodes if abs(coordinates[node][0]) < 1e-12]
    ymin = [node for node in nodes if abs(coordinates[node][1]) < 1e-12]
    zmin = [node for node in nodes if abs(coordinates[node][2]) < 1e-12]
    xmax = [node for node in nodes if abs(coordinates[node][0] - lx) < 1e-12]
    target = (1.5, 0.5, 0.1) if kind == "notch" else (lx / 2, ly / 2, lz / 2)
    probe_element = min(
        range(1, len(elements) + 1),
        key=lambda index: sum(
            (element_centers[index - 1][axis] - target[axis]) ** 2
            for axis in range(3)
        ),
    )
    lines = [
        f"** SpjutSim FEA independent reference: {case_id}",
        "** Generated by tools/generate-calculix-reference.py; SI units.",
        "*NODE",
    ]
    lines.extend(
        f"{node}, {coordinates[node][0]:.12g}, {coordinates[node][1]:.12g}, {coordinates[node][2]:.12g}"
        for node in nodes
    )
    lines.append("*ELEMENT, TYPE=C3D8, ELSET=EALL")
    lines.extend(
        f"{index}, " + ", ".join(str(node) for node in element)
        for index, element in enumerate(elements, 1)
    )
    lines.extend(format_set("NALL", nodes))
    lines.extend(format_set("XMIN", xmin))
    lines.extend(format_set("YMIN", ymin))
    lines.extend(format_set("ZMIN", zmin))
    lines.extend(format_set("XMAX", xmax))
    lines.extend(["*ELSET, ELSET=PROBE", str(probe_element)])
    lines.extend([
        "*SOLID SECTION, ELSET=EALL, MATERIAL=VALIDATION",
        "*MATERIAL, NAME=VALIDATION",
        "*ELASTIC",
        "1.0E9, 0.25",
        "*DENSITY",
        "1000.",
        "*BOUNDARY",
    ])
    if kind in ("bending", "notch"):
        lines.append("XMIN, 1, 3, 0.")
    else:
        lines.extend(["XMIN, 1, 1, 0.", "YMIN, 2, 2, 0.", "ZMIN, 3, 3, 0."])
    lines.extend(["*STEP", "*STATIC"])
    if kind == "gravity":
        lines.extend(["*DLOAD", "EALL, GRAV, 9.81, 0., 0., -1."])
    else:
        direction = 3 if kind == "bending" else 1
        total = -1000.0 if kind in ("bending", "pressure") else 1000.0
        weights = []
        for node in xmax:
            _, y, z = coordinates[node]
            weight = (1 if y in (0.0, ly) else 2) * (1 if z in (0.0, lz) else 2)
            weights.append((node, weight))
        weight_sum = sum(weight for _, weight in weights)
        lines.append("*CLOAD")
        lines.extend(f"{node}, {direction}, {total * weight / weight_sum:.15g}" for node, weight in weights)
    lines.extend(["*NODE PRINT, NSET=XMAX", "U"])
    reaction_sets = ["XMIN"] if kind in ("bending", "notch") else ["XMIN", "YMIN", "ZMIN"]
    for name in reaction_sets:
        lines.extend([f"*NODE PRINT, NSET={name}, TOTALS=YES", "RF"])
    lines.extend(["*EL PRINT, ELSET=PROBE", "S", "*END STEP", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()
    for case_id, definition in CASES.items():
        directory = args.output / case_id
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "case.inp").write_text(generate_case(case_id, definition), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
